### ISSUE TITLE
Schachbrett Koordinaten

### ISSUE THREAD

**Issue by GetDautz** [adrianmoerk/RoboChess#9]
## Aufgabe
Für jedes Schachbrettfeld soll die Mitte als Koordinaten ermittelt und aufgenommen werden.  
Überlegen, wie die Koordinaten gespeichert werden.  

## Ideen:  
- Objektattribut für jedes Feld
- 2D-Array
- ...

**Comment by Ping-uin** [comment]
Koordinaten werden ausgehend von a1 berechnet;
Der Roboter kann sich zu jeder Koordinate bewegen
